version: '3.8'

services:
  app1:
    build: .
    container_name: app1
    ports:
      - "5001:5000"

  app2:
    build: .
    container_name: app2
    ports:
      - "5002:5000"

  app3:
    build: .
    container_name: app3
    ports:
      - "5003:5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "6080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3
